language: ruby

env:
  global:
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install bundler
  - bundle install --without=documentation

jobs:
  include:
    - &test
      stage: test
      name: RVM 2.0
      rvm:: 2.0
      script:
        - bundle exec rake spec
        - bundle exec danger

    - <<: *test
      name: RVM 2.3.1
      rvm:: 2.3.1

    - <<: *test
      name: RVM 2.5.1
      rvm:: 2.5.1

stages:
  - test

branches:
  only:
    - master
    - develop
  except:
    - "/^[^\\/]+\\/\\d+(?:\\.\\d+)+\\/\\d+$/"

cache:
  bundler: true
  pip: true
  directories:
    - $HOME/vendor/bundle/
    - $HOME/.rvm/
    - $HOME/Library/Caches/Homebrew
