language: ruby

env:
  global:
    - CC_TEST_REPORTER_ID=""
    - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - gem install bundler
  - bundle install --without=documentation
  - pip3 install proselint
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

jobs:
  include:
    - &test
      stage: test
      name: run rake spec
      rvm:: 2.0
      before_script:
        - "./cc-test-reporter before-build"
      script:
        - bundle exec rake spec
        - bundle exec danger
      after_success:
        - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"

    - <<: *test
      name: RVM 2.3.1
      rvm:: 2.3.1

    - <<: *test
      name: RVM 2.5.1
      rvm:: 2.5.1

stages:
  - test

branches:
  only:
    - master
    - develop
  except:
    - "/^[^\\/]+\\/\\d+(?:\\.\\d+)+\\/\\d+$/"

cache:
  bundler: true
  pip: true
  directories:
    - $HOME/vendor/bundle/
    - $HOME/.rvm/
    - $HOME/Library/Caches/Homebrew
