---
name: Automerge
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.8.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "automerge, !wip,!work in progress"
          MERGE_METHOD: "squash"
          UPDATE_LABELS: "automerge"
